# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-opsgenie-team
  description: This component is responsible for provisioning Opsgenie teams and related services, rules, schedules
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component








